force-app/main/default/objects/DF_Duplicate_Field_Config__mdt/DF_Duplicate_Field_Config__mdt.object-meta.xml
<CustomObject>
    <label>DF Duplicate Field Config</label>
    <pluralLabel>DF Duplicate Field Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Duplicate_Finder_Setting__c/Duplicate_Finder_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to restrict number of duplicate records display on screen.</description>
    <label>Duplicate Finder Setting</label>
</CustomObject>

force-app/main/default/objects/Duplicate_Finder_Setting__c/fields/Record_Limit__c.field-meta.xml
<CustomField>
    <fullName>Record_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>It should be 5 or less than 5.</description>
    <label>Record Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DF_ConfigurationController.cls
public class DF_ConfigurationController {
    
    public class ConfigurationStatus {
        @AuraEnabled public Boolean isCustomMetadataConfigured;
        @AuraEnabled public Boolean isRecordLimitConfigured;
        @AuraEnabled public Integer recordLimit;
        @AuraEnabled public Boolean isReady;
    }

    @AuraEnabled(cacheable=true)
    public static ConfigurationStatus getConfigurationStatus() {
        ConfigurationStatus status = new ConfigurationStatus();

        status.isCustomMetadataConfigured = [SELECT Count() FROM DF_Duplicate_Field_Config__mdt] > 0;
        Duplicate_Finder_Setting__c setting = Duplicate_Finder_Setting__c.getOrgDefaults();

        if(setting != null && setting.Record_Limit__c != null){
            status.isRecordLimitConfigured = true;
            status.recordLimit = Integer.valueOf(setting.Record_Limit__c);
        }else {
            status.isRecordLimitConfigured = false;
        }

        status.isReady = status.isCustomMetadataConfigured && status.isRecordLimitConfigured;
        return status;
    }
    
}